"""Add QMS features

Revision ID: af6142147d08
Revises: 
Create Date: 2025-10-27 09:08:32.052085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af6142147d08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quality_objectives',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('objective_number', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=255), nullable=True),
    sa.Column('current_value', sa.String(length=255), nullable=True),
    sa.Column('unit_of_measure', sa.String(length=100), nullable=True),
    sa.Column('measurement_method', sa.Text(), nullable=True),
    sa.Column('measurement_frequency', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'ACHIEVED', 'DELAYED', 'CANCELLED', name='objectivestatus'), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=True),
    sa.Column('responsible_person', sa.String(length=36), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=False),
    sa.Column('achieved_date', sa.Date(), nullable=True),
    sa.Column('iso_standard_id', sa.String(length=36), nullable=True),
    sa.Column('related_clause', sa.String(length=20), nullable=True),
    sa.Column('linked_processes', sa.Text(), nullable=True),
    sa.Column('linked_risks', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('progress_notes', sa.Text(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('next_review_date', sa.Date(), nullable=True),
    sa.Column('review_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['iso_standard_id'], ['iso_standards.id'], ),
    sa.ForeignKeyConstraint(['responsible_person'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_objectives_objective_number'), 'quality_objectives', ['objective_number'], unique=True)
    op.create_index(op.f('ix_quality_objectives_status'), 'quality_objectives', ['status'], unique=False)
    op.create_index(op.f('ix_quality_objectives_target_date'), 'quality_objectives', ['target_date'], unique=False)
    op.create_index(op.f('ix_quality_objectives_workspace_id'), 'quality_objectives', ['workspace_id'], unique=False)
    op.create_table('quality_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('previous_version_id', sa.String(length=36), nullable=True),
    sa.Column('policy_title', sa.String(length=500), nullable=False),
    sa.Column('policy_statement', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('quality_commitments', sa.Text(), nullable=True),
    sa.Column('customer_focus_commitment', sa.Text(), nullable=True),
    sa.Column('improvement_commitment', sa.Text(), nullable=True),
    sa.Column('compliance_commitment', sa.Text(), nullable=True),
    sa.Column('policy_owner', sa.String(length=36), nullable=False),
    sa.Column('department', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('superseded_date', sa.Date(), nullable=True),
    sa.Column('approved_by', sa.String(length=36), nullable=True),
    sa.Column('approval_date', sa.Date(), nullable=True),
    sa.Column('approval_signature_path', sa.String(length=1000), nullable=True),
    sa.Column('communication_plan', sa.Text(), nullable=True),
    sa.Column('communicated_to', sa.Text(), nullable=True),
    sa.Column('awareness_training_required', sa.Boolean(), nullable=True),
    sa.Column('awareness_evidence', sa.Text(), nullable=True),
    sa.Column('document_location', sa.String(length=1000), nullable=True),
    sa.Column('publicly_available', sa.Boolean(), nullable=True),
    sa.Column('external_url', sa.String(length=500), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('changes_summary', sa.Text(), nullable=True),
    sa.Column('impact_assessment', sa.Text(), nullable=True),
    sa.Column('last_review_date', sa.Date(), nullable=True),
    sa.Column('review_frequency_months', sa.Integer(), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('iso_standard_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('actual_resolution_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['iso_standard_id'], ['iso_standards.id'], ),
    sa.ForeignKeyConstraint(['policy_owner'], ['users.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['quality_policies.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quality_policies_effective_date'), 'quality_policies', ['effective_date'], unique=False)
    op.create_index(op.f('ix_quality_policies_policy_number'), 'quality_policies', ['policy_number'], unique=True)
    op.create_index(op.f('ix_quality_policies_status'), 'quality_policies', ['status'], unique=False)
    op.create_index(op.f('ix_quality_policies_version'), 'quality_policies', ['version'], unique=False)
    op.create_index(op.f('ix_quality_policies_workspace_id'), 'quality_policies', ['workspace_id'], unique=False)
    op.create_table('requirements_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('review_number', sa.String(length=50), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=255), nullable=False),
    sa.Column('customer_contact', sa.String(length=255), nullable=True),
    sa.Column('product_service_name', sa.String(length=500), nullable=False),
    sa.Column('contract_number', sa.String(length=100), nullable=True),
    sa.Column('order_number', sa.String(length=100), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('reviewed_by', sa.String(length=36), nullable=False),
    sa.Column('customer_requirements', sa.Text(), nullable=False),
    sa.Column('regulatory_requirements', sa.Text(), nullable=True),
    sa.Column('statutory_requirements', sa.Text(), nullable=True),
    sa.Column('delivery_requirements', sa.Text(), nullable=True),
    sa.Column('capability_to_meet', sa.Boolean(), nullable=True),
    sa.Column('capability_assessment', sa.Text(), nullable=True),
    sa.Column('resource_availability', sa.Text(), nullable=True),
    sa.Column('differences_from_previous', sa.Text(), nullable=True),
    sa.Column('unresolved_issues', sa.Text(), nullable=True),
    sa.Column('clarifications_needed', sa.Text(), nullable=True),
    sa.Column('review_result', sa.String(length=50), nullable=False),
    sa.Column('approval_conditions', sa.Text(), nullable=True),
    sa.Column('rejection_reasons', sa.Text(), nullable=True),
    sa.Column('review_participants', sa.Text(), nullable=True),
    sa.Column('customer_representative', sa.String(length=255), nullable=True),
    sa.Column('supporting_documents', sa.Text(), nullable=True),
    sa.Column('meeting_minutes', sa.Text(), nullable=True),
    sa.Column('follow_up_actions', sa.Text(), nullable=True),
    sa.Column('contract_signed_date', sa.Date(), nullable=True),
    sa.Column('iso_standard_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['iso_standard_id'], ['iso_standards.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_reviews_contract_number'), 'requirements_reviews', ['contract_number'], unique=False)
    op.create_index(op.f('ix_requirements_reviews_customer_name'), 'requirements_reviews', ['customer_name'], unique=False)
    op.create_index(op.f('ix_requirements_reviews_review_date'), 'requirements_reviews', ['review_date'], unique=False)
    op.create_index(op.f('ix_requirements_reviews_review_number'), 'requirements_reviews', ['review_number'], unique=True)
    op.create_index(op.f('ix_requirements_reviews_workspace_id'), 'requirements_reviews', ['workspace_id'], unique=False)
    op.drop_index(op.f('ix_customer_complaints_status'), table_name='customer_complaints')
    op.drop_column('customer_complaints', 'status')
    op.drop_column('customer_complaints', 'actual_resolution_date')
    op.drop_column('customer_complaints', 'updated_at')
    op.drop_column('customer_complaints', 'created_at')
    op.add_column('iso_standards', sa.Column('qms_scope_statement', sa.Text(), nullable=True))
    op.add_column('iso_standards', sa.Column('qms_exclusions', sa.Text(), nullable=True))
    op.add_column('iso_standards', sa.Column('qms_applicability', sa.Text(), nullable=True))
    op.add_column('iso_standards', sa.Column('qms_boundaries', sa.Text(), nullable=True))
    op.add_column('training_records', sa.Column('employee_name', sa.String(length=255), nullable=True))
    op.add_column('training_records', sa.Column('employee_number', sa.String(length=100), nullable=True))
    op.add_column('training_records', sa.Column('job_role', sa.String(length=255), nullable=True))
    op.add_column('training_records', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('training_records', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('training_records', sa.Column('reminder_sent', sa.Boolean(), nullable=True))
    op.add_column('training_records', sa.Column('competence_achieved', sa.Boolean(), nullable=True))
    op.add_column('training_records', sa.Column('evaluation_method', sa.String(length=255), nullable=True))
    op.add_column('training_records', sa.Column('evaluation_score', sa.Float(), nullable=True))
    op.create_index(op.f('ix_training_records_expiry_date'), 'training_records', ['expiry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_records_expiry_date'), table_name='training_records')
    op.drop_column('training_records', 'evaluation_score')
    op.drop_column('training_records', 'evaluation_method')
    op.drop_column('training_records', 'competence_achieved')
    op.drop_column('training_records', 'reminder_sent')
    op.drop_column('training_records', 'expiry_date')
    op.drop_column('training_records', 'department')
    op.drop_column('training_records', 'job_role')
    op.drop_column('training_records', 'employee_number')
    op.drop_column('training_records', 'employee_name')
    op.drop_column('iso_standards', 'qms_boundaries')
    op.drop_column('iso_standards', 'qms_applicability')
    op.drop_column('iso_standards', 'qms_exclusions')
    op.drop_column('iso_standards', 'qms_scope_statement')
    op.add_column('customer_complaints', sa.Column('created_at', sa.DATETIME(), nullable=True))
    op.add_column('customer_complaints', sa.Column('updated_at', sa.DATETIME(), nullable=True))
    op.add_column('customer_complaints', sa.Column('actual_resolution_date', sa.DATE(), nullable=True))
    op.add_column('customer_complaints', sa.Column('status', sa.VARCHAR(length=20), nullable=True))
    op.create_index(op.f('ix_customer_complaints_status'), 'customer_complaints', ['status'], unique=False)
    op.drop_index(op.f('ix_requirements_reviews_workspace_id'), table_name='requirements_reviews')
    op.drop_index(op.f('ix_requirements_reviews_review_number'), table_name='requirements_reviews')
    op.drop_index(op.f('ix_requirements_reviews_review_date'), table_name='requirements_reviews')
    op.drop_index(op.f('ix_requirements_reviews_customer_name'), table_name='requirements_reviews')
    op.drop_index(op.f('ix_requirements_reviews_contract_number'), table_name='requirements_reviews')
    op.drop_table('requirements_reviews')
    op.drop_index(op.f('ix_quality_policies_workspace_id'), table_name='quality_policies')
    op.drop_index(op.f('ix_quality_policies_version'), table_name='quality_policies')
    op.drop_index(op.f('ix_quality_policies_status'), table_name='quality_policies')
    op.drop_index(op.f('ix_quality_policies_policy_number'), table_name='quality_policies')
    op.drop_index(op.f('ix_quality_policies_effective_date'), table_name='quality_policies')
    op.drop_table('quality_policies')
    op.drop_index(op.f('ix_quality_objectives_workspace_id'), table_name='quality_objectives')
    op.drop_index(op.f('ix_quality_objectives_target_date'), table_name='quality_objectives')
    op.drop_index(op.f('ix_quality_objectives_status'), table_name='quality_objectives')
    op.drop_index(op.f('ix_quality_objectives_objective_number'), table_name='quality_objectives')
    op.drop_table('quality_objectives')
    # ### end Alembic commands ###
